from pathlib import Path
import re, json, datetime
root=Path('/mnt/data/lunarmagic-seo-site')
BASE='https://lunarmagic.com'
phone='+1 540.300.5288'
email='jason@lunarmagic.com'
brand='Lunar Magic'

cities=[
('new-york-city-ny','New York City','NY'),('philadelphia-pa','Philadelphia','PA'),('washington-dc','Washington','DC'),('boston-ma','Boston','MA'),('baltimore-md','Baltimore','MD'),('richmond-va','Richmond','VA'),('virginia-beach-va','Virginia Beach','VA'),('charlotte-nc','Charlotte','NC'),('raleigh-nc','Raleigh','NC'),('atlanta-ga','Atlanta','GA'),('orlando-fl','Orlando','FL'),('tampa-fl','Tampa','FL'),('miami-fl','Miami','FL'),('jacksonville-fl','Jacksonville','FL'),('nashville-tn','Nashville','TN'),('knoxville-tn','Knoxville','TN'),('charleston-sc','Charleston','SC'),('columbia-sc','Columbia','SC'),('savannah-ga','Savannah','GA'),('pittsburgh-pa','Pittsburgh','PA'),('columbus-oh','Columbus','OH'),('cleveland-oh','Cleveland','OH'),('cincinnati-oh','Cincinnati','OH'),('detroit-mi','Detroit','MI'),('indianapolis-in','Indianapolis','IN'),('chicago-il','Chicago','IL'),('milwaukee-wi','Milwaukee','WI'),('louisville-ky','Louisville','KY'),('lexington-ky','Lexington','KY'),('st-louis-mo','St. Louis','MO'),('birmingham-al','Birmingham','AL'),('huntsville-al','Huntsville','AL'),('new-orleans-la','New Orleans','LA'),('hartford-ct','Hartford','CT'),('providence-ri','Providence','RI'),('newark-nj','Newark','NJ'),('buffalo-ny','Buffalo','NY'),('rochester-ny','Rochester','NY')]
services=[('weddings','Wedding Drone Light Shows','romantic aerial storytelling for weddings, proposals, and private celebrations'),('corporate-events','Corporate Drone Light Shows','branded product launches, conferences, galas, and employee events'),('festivals-fairs','Festival & Fair Drone Shows','family-friendly entertainment for fairs, festivals, and destination events'),('sports-entertainment','Sports & Entertainment Drone Shows','halftime shows, fan experiences, arena-adjacent activations, and branded reveals'),('municipal-events','Municipal & Public Celebration Drone Shows','Fourth of July alternatives, holiday celebrations, tourism events, and civic milestones'),('nonprofits-causes','Nonprofit & Cause Drone Shows','mission-driven storytelling for fundraisers, awareness campaigns, and community moments')]

def slugify(s): return re.sub('[^a-z0-9]+','-',s.lower()).strip('-')

def meta(title, desc, path):
    return f'''<title>{title}</title>\n<meta name="description" content="{desc}">\n<link rel="canonical" href="{BASE}{path}">\n<meta property="og:title" content="{title}">\n<meta property="og:description" content="{desc}">\n<meta property="og:url" content="{BASE}{path}">\n<meta property="og:type" content="website">\n<meta property="og:image" content="{BASE}/assets/home-hero.png">'''

def layout(title, desc, path, body, schema=None):
    schema_tag=f'<script type="application/ld+json">{json.dumps(schema,indent=2)}</script>' if schema else ''
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">{meta(title,desc,path)}<link rel="stylesheet" href="/styles.css">{schema_tag}</head><body><header class="site-header"><a class="brand" href="/"><img src="/assets/home-hero.png" alt="Lunar Magic drone light shows logo and contact card"><span>{brand}</span></a><nav><a href="/services/">Services</a><a href="/locations/">Locations</a><a href="/gallery.html">Gallery</a><a class="cta" href="/contact.html">Request a Show</a></nav></header><main>{body}</main><footer><div><strong>Lunar Magic LLC</strong><br>Stories Written in the Sky<br><a href="tel:+15403005288">{phone}</a> · <a href="mailto:{email}">{email}</a></div><nav><a href="/services/">Services</a><a href="/locations/">Locations</a><a href="/sitemap.xml">Sitemap</a></nav></footer></body></html>'''

css='''
:root{--purple:#18042e;--purple2:#27004a;--ink:#fff;--muted:#e9dff3;--gold:#e8dba7;--card:#0a0610}*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;background:#050208;color:var(--ink);line-height:1.6}a{color:#fff}.site-header{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:24px;align-items:center;padding:14px 6vw;background:rgba(18,3,34,.92);backdrop-filter:blur(10px);border-bottom:1px solid rgba(255,255,255,.12)}.brand{display:flex;align-items:center;gap:12px;text-decoration:none;font-size:1.2rem;font-weight:700}.brand img{width:54px;height:54px;object-fit:cover;border-radius:10px}.site-header nav,footer nav{display:flex;gap:18px;flex-wrap:wrap;align-items:center}.site-header a{text-decoration:none}.cta,.button{background:linear-gradient(135deg,#fff,#d8c6ff);color:#19042d!important;border-radius:999px;padding:.75rem 1rem;font-weight:800;text-decoration:none;display:inline-block}.hero{padding:88px 6vw;background:radial-gradient(circle at 70% 20%,#54208b,transparent 34%),linear-gradient(135deg,var(--purple),#050208)}.hero-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:36px;align-items:center;max-width:1180px;margin:auto}.hero h1{font-size:clamp(2.25rem,6vw,5rem);line-height:1.05;margin:0 0 18px}.eyebrow{color:var(--gold);font-weight:800;letter-spacing:.08em;text-transform:uppercase}.lead{font-size:1.25rem;color:var(--muted)}.hero img,.section img{max-width:100%;border-radius:24px;border:1px solid rgba(255,255,255,.15);box-shadow:0 30px 80px rgba(0,0,0,.45)}.section{padding:70px 6vw}.wrap{max-width:1180px;margin:auto}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}.card{background:linear-gradient(180deg,#170526,#0a0610);border:1px solid rgba(255,255,255,.12);padding:24px;border-radius:22px}.card h3{margin-top:0}.split{display:grid;grid-template-columns:1fr 1fr;gap:34px;align-items:center}.city-grid{columns:3 260px}.city-grid a{display:block;padding:10px 0}.banner{background:#18042e;padding:36px 6vw;text-align:center}.faq details{background:#100718;margin:12px 0;padding:18px;border-radius:16px}form{display:grid;gap:14px;max-width:680px}input,textarea,select{padding:15px;border-radius:12px;border:1px solid #80639e;background:#130522;color:white}footer{padding:40px 6vw;border-top:1px solid rgba(255,255,255,.12);display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap;background:#09030f}@media(max-width:800px){.hero-grid,.split{grid-template-columns:1fr}.site-header{position:static;align-items:flex-start;flex-direction:column}.hero{padding-top:48px}}
'''
(root/'styles.css').write_text(css)
org_schema={"@context":"https://schema.org","@type":"LocalBusiness","name":"Lunar Magic LLC","url":BASE,"email":email,"telephone":"+15403005288","description":"Custom drone light shows for public celebrations, corporate events, weddings, festivals, sports entertainment, nonprofits, and city events across the United States.","areaServed":["United States","Virginia","Washington DC","New York","Pennsylvania","North Carolina","Georgia","Florida","Ohio","Michigan","Illinois","Tennessee","South Carolina","Kentucky","Alabama"]}

home_body='''<section class="hero"><div class="hero-grid"><div><p class="eyebrow">Drone light shows across the USA</p><h1>Stories Written in the Sky</h1><p class="lead">Lunar Magic creates custom, eco-friendly drone light shows for cities, brands, weddings, festivals, sports events, and private celebrations.</p><p><a class="button" href="/contact.html">Request a Drone Show Quote</a></p></div><img src="/assets/home-hero.png" alt="Lunar Magic drone light show contact card"></div></section><section class="section"><div class="wrap split"><div><h2>Fireworks alternative. Brand spectacle. Crowd memory.</h2><p>A drone light show is a choreographed aerial performance using LED-equipped drones to form logos, animations, messages, mascots, and cinematic scenes in the night sky. Lunar Magic designs custom shows that are reusable, low-noise, smoke-free, and built around your story.</p></div><img src="/assets/safe-silent.png" alt="Peaceful drone show alternative to fireworks"></div></section><section class="section"><div class="wrap"><h2>Drone show services</h2><div class="cards">'''
for slug,title,desc in services:
    home_body+=f'<a class="card" href="/services/{slug}.html"><h3>{title}</h3><p>Custom {desc}.</p></a>'
home_body+='''</div></div></section><section class="section"><div class="wrap"><h2>Major Eastern USA service areas</h2><p>Lunar Magic can support events across Virginia and the eastern half of the United States, including major metro areas, tourism destinations, fairgrounds, campuses, stadium districts, and waterfront venues.</p><div class="city-grid">'''
for slug,city,state in cities: home_body+=f'<a href="/locations/{slug}.html">Drone light shows in {city}, {state}</a>'
home_body+='''</div></div></section><section class="banner"><h2>Ready to replace ordinary fireworks with something unforgettable?</h2><a class="button" href="/contact.html">Plan Your Show</a></section>'''
(root/'index.html').write_text(layout('Lunar Magic Drone Light Shows | Custom Aerial Entertainment Across the USA','Custom drone light shows for cities, brands, weddings, festivals, sports, nonprofits, and private events across the eastern USA. Request a Lunar Magic show.', '/', home_body, org_schema))

(root/'services'/'index.html').write_text(layout('Drone Light Show Services | Lunar Magic','Explore Lunar Magic drone light show services for weddings, corporate events, festivals, sports, municipal events, nonprofits, and private celebrations.','/services/','<section class="hero"><div class="wrap"><h1>Drone Light Show Services</h1><p class="lead">Custom aerial storytelling for public and private events.</p></div></section><section class="section"><div class="wrap"><div class="cards">'+''.join(f'<a class="card" href="/services/{s}.html"><h3>{t}</h3><p>{d.capitalize()}.</p></a>' for s,t,d in services)+'</div></div></section>',org_schema))

for slug,title,desc in services:
    body=f'''<section class="hero"><div class="wrap"><p class="eyebrow">Lunar Magic Services</p><h1>{title}</h1><p class="lead">{brand} creates {desc} with custom animations, messages, logos, and music-ready aerial choreography.</p><a class="button" href="/contact.html">Request a {title} Quote</a></div></section><section class="section"><div class="wrap split"><div><h2>Built around your story</h2><p>Every Lunar Magic show can be built from scratch. Your logo, mascot, colors, message, proposal, campaign, or community theme can be rendered in the night sky using precise LED drone formations.</p><p>Drone shows are a strong choice when you want a safer, quieter, cleaner alternative to fireworks without sacrificing spectacle.</p></div><img src="/assets/customizable.png" alt="Custom drone show formation"></div></section><section class="section faq"><div class="wrap"><h2>Common questions</h2><details open><summary>Can the show include our logo?</summary><p>Yes. Logos, mascots, slogans, countdowns, hearts, stars, product shapes, and themed animations can be designed into the choreography.</p></details><details><summary>Can Lunar Magic travel?</summary><p>Yes. Lunar Magic is positioned to support events in Virginia and across major cities in the eastern United States.</p></details></div></section>'''
    (root/'services'/f'{slug}.html').write_text(layout(f'{title} | Lunar Magic',f'{title} by Lunar Magic: custom, eco-friendly drone light shows for {desc}.',f'/services/{slug}.html',body,org_schema))

loc_index='<section class="hero"><div class="wrap"><h1>Drone Light Show Locations</h1><p class="lead">SEO landing pages for major Eastern USA cities.</p></div></section><section class="section"><div class="wrap city-grid">'+''.join(f'<a href="/locations/{slug}.html">{city}, {state}</a>' for slug,city,state in cities)+'</div></section>'
(root/'locations'/'index.html').write_text(layout('Drone Light Show Locations | Lunar Magic','Lunar Magic provides custom drone light shows for cities and event organizers across major Eastern USA markets.','/locations/',loc_index,org_schema))
for slug,city,state in cities:
    body=f'''<section class="hero"><div class="wrap"><p class="eyebrow">Drone light shows in {city}</p><h1>{city}, {state} Drone Light Shows</h1><p class="lead">Custom aerial entertainment for public celebrations, festivals, corporate events, weddings, sports, and private events in the {city} area.</p><a class="button" href="/contact.html">Request a {city} Drone Show Quote</a></div></section><section class="section"><div class="wrap split"><div><h2>Bring Lunar Magic to {city}</h2><p>Lunar Magic designs choreographed drone light shows that turn the sky into branded, emotional, family-friendly entertainment. Shows can feature logos, mascots, animated scenes, love stories, holiday moments, civic pride, sponsor messages, and custom countdowns.</p><p>For {city} event planners, drone shows offer a cleaner and quieter alternative to traditional fireworks, with no smoke, no debris, and no explosive booms.</p></div><img src="/assets/eco-friendly.png" alt="Eco-friendly drone light show alternative"></div></section><section class="section"><div class="wrap"><h2>Popular {city} event types</h2><div class="cards"><div class="card"><h3>City celebrations</h3><p>Holiday events, tourism activations, waterfront celebrations, and community nights.</p></div><div class="card"><h3>Corporate events</h3><p>Product launches, conferences, grand openings, employee celebrations, and sponsor activations.</p></div><div class="card"><h3>Private events</h3><p>Weddings, proposals, milestone birthdays, and luxury celebrations.</p></div></div></div></section><section class="banner"><h2>Planning a show near {city}?</h2><a class="button" href="/contact.html">Contact Lunar Magic</a></section>'''
    (root/'locations'/f'{slug}.html').write_text(layout(f'{city}, {state} Drone Light Shows | Lunar Magic',f'Custom drone light shows in {city}, {state} for cities, festivals, weddings, brands, corporate events, sports, and private celebrations.',f'/locations/{slug}.html',body,org_schema))

(root/'gallery.html').write_text(layout('Drone Light Show Gallery | Lunar Magic','Watch Lunar Magic drone light show examples and see custom aerial artwork, logos, and animations in the night sky.','/gallery.html','<section class="hero"><div class="wrap"><h1>Drone Light Show Gallery</h1><p class="lead">A growing collection of Lunar Magic aerial artwork.</p></div></section><section class="section"><div class="wrap cards"><img src="/assets/home-hero.png" alt="Drone formation by Lunar Magic"><img src="/assets/customizable.png" alt="Customizable drone light show"><img src="/assets/safe-silent.png" alt="Safe silent drone show"></div></section>',org_schema))
(root/'contact.html').write_text(layout('Request a Drone Light Show Quote | Lunar Magic','Contact Lunar Magic to plan a custom drone light show for your city, brand, wedding, festival, sports event, or private celebration.','/contact.html',f'<section class="hero"><div class="wrap"><h1>Request a Drone Light Show Quote</h1><p class="lead">Tell us about your event, location, audience size, desired date, and creative vision.</p><p><a href="tel:+15403005288">{phone}</a> · <a href="mailto:{email}">{email}</a></p></div></section><section class="section"><div class="wrap"><form action="mailto:{email}" method="post" enctype="text/plain"><input name="name" placeholder="Name*" required><input name="organization" placeholder="Organization"><input name="email" type="email" placeholder="Email*" required><input name="phone" placeholder="Phone"><select name="event_type"><option>City / public celebration</option><option>Corporate event</option><option>Wedding / private event</option><option>Festival / fair</option><option>Sports / entertainment</option><option>Nonprofit / cause</option></select><textarea name="message" rows="8" placeholder="Event location, date, audience size, and creative ideas*" required></textarea><button class="button" type="submit">Send Request</button></form></div></section>',org_schema))

urls=['/','/services/','/locations/','/gallery.html','/contact.html']+[f'/services/{s}.html' for s,_,_ in services]+[f'/locations/{s}.html' for s,_,_ in cities]
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{BASE}{u}</loc><lastmod>{datetime.date.today()}</lastmod><changefreq>monthly</changefreq><priority>{"1.0" if u=="/" else "0.8"}</priority></url>\n' for u in urls)+'</urlset>')
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://lunarmagic.com/sitemap.xml\n')
(root/'README.md').write_text(f'''# Lunar Magic SEO Website\n\nStatic, GitHub-ready SEO website for https://lunarmagic.com.\n\n## Deploy\n1. Create or open the Lunar Magic GitHub repo.\n2. Upload all files in this folder to the repo root.\n3. Enable GitHub Pages or connect the repo to Netlify/Vercel/Cloudflare Pages.\n4. Point lunarmagic.com DNS at the host.\n5. Submit `/sitemap.xml` in Google Search Console and Bing Webmaster Tools.\n\n## Included\n- Homepage\n- Service pages\n- 38 Eastern USA city landing pages\n- SEO titles/descriptions/canonicals/Open Graph tags\n- LocalBusiness schema\n- robots.txt and sitemap.xml\n- Existing visual assets from screenshots\n''')
